#!/usr/bin/with-contenv bash

silent() {
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    "$@"
  else
    "$@" > /dev/null 2>&1
  fi
}

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  set -x
fi

### Set Defaults
NGINX_WEBROOT=${NGINX_WEBROOT:-"/www/html"}
PHP_APC_SHM_SIZE=${PHP_APC_SHM_SIZE:-"128M"}
PHP_ENABLE_AMQP=${PHP_ENABLE_AMQP:-"FALSE"}
PHP_ENABLE_APCU=${PHP_ENABLE_APCU:-"TRUE"}
PHP_ENABLE_BCMATH=${PHP_ENABLE_BCMATH:-"TRUE"}
PHP_ENABLE_BZ2=${PHP_ENABLE_BZ2:-"FALSE"}
PHP_ENABLE_CALENDAR=${PHP_ENABLE_CALENDAR:-"FALSE"}
PHP_ENABLE_CREATE_SAMPLE_PHP=${PHP_ENABLE_CREATE_SAMPLE_PHP:-"TRUE"}
PHP_ENABLE_CTYPE=${PHP_ENABLE_CTYPE:-"TRUE"}
PHP_ENABLE_CURL=${PHP_ENABLE_CURL:-"TRUE"}
PHP_ENABLE_DBA=${PHP_ENABLE_DBA:-"FALSE"}
PHP_ENABLE_DISPLAY_ERRORS=${PHP_ENABLE_DISPLAY_ERRORS:-"TRUE"}
PHP_ENABLE_DOM=${PHP_ENABLE_DOM:-"TRUE"}
PHP_ENABLE_EMBED=${PHP_ENABLE_EMBED:-"FALSE"}
PHP_ENABLE_ENCHANT=${PHP_ENABLE_ENCHANT:-"FALSE"}
PHP_ENABLE_EXIF=${PHP_ENABLE_EXIF:-"FALSE"}
PHP_ENABLE_FILEINFO=${PHP_ENABLE_FILEINFO:-"FALSE"}
PHP_ENABLE_FTP=${PHP_ENABLE_FTP:-"FALSE"}
PHP_ENABLE_GD=${PHP_ENABLE_GD:-"TRUE"}
PHP_ENABLE_GETTEXT=${PHP_ENABLE_GETTEXT:-"FALSE"}
PHP_ENABLE_GMP=${PHP_ENABLE_GMP:-"FALSE"}
PHP_ENABLE_ICONV=${PHP_ENABLE_ICONV:-"TRUE"}
PHP_ENABLE_IGBINARY=${PHP_ENABLE_IGBINARY:-"FALSE"}
PHP_ENABLE_IMAGICK=${PHP_ENABLE_IMAGICK:-"FALSE"}
PHP_ENABLE_IMAP=${PHP_ENABLE_IMAP:-"TRUE"}
PHP_ENABLE_INTL=${PHP_ENABLE_INTL:-"TRUE"}
PHP_ENABLE_JSON=${PHP_ENABLE_JSON:-"TRUE"}
PHP_ENABLE_KITCHENSINK=${PHP_ENABLE_KITCHENSINK:-"FALSE"}
PHP_ENABLE_LDAP=${PHP_ENABLE_LDAP:-"FALSE"}
PHP_ENABLE_MAILPARSE=${PHP_ENABLE_MAILPARSE:-"FALSE"}
PHP_ENABLE_MBSTRING=${PHP_ENABLE_MBSTRING:-"TRUE"}
PHP_ENABLE_MCRYPT=${PHP_ENABLE_MCRYPT:-"TRUE"}
PHP_ENABLE_MEMCACHED=${PHP_ENABLE_MEMCACHED:-"FALSE"}
PHP_ENABLE_MYSQLI=${PHP_ENABLE_MYSQLI:-"FALSE"}
PHP_ENABLE_MYSQLND=${PHP_ENABLE_MYSQLND:-"TRUE"}
PHP_ENABLE_ODBC=${PHP_ENABLE_ODBC:-"FALSE"}
PHP_ENABLE_OPCACHE=${PHP_ENABLE_OPCACHE:-"TRUE"}
PHP_ENABLE_OPENSSL=${PHP_ENABLE_OPENSSL:-"TRUE"}
PHP_ENABLE_PCNTL=${PHP_ENABLE_PCNTL:-"FALSE"}
PHP_ENABLE_PDO=${PHP_ENABLE_PDO:-"FALSE"}
PHP_ENABLE_PDO_DBLIB=${PHP_ENABLE_PDO_MYSQL:-"FALSE"}
PHP_ENABLE_PDO_MYSQL=${PHP_ENABLE_PDO_MYSQL:-"FALSE"}
PHP_ENABLE_PDO_PGSQL=${PHP_ENABLE_PDO_PGSQL:-"FALSE"}
PHP_ENABLE_PDO_ODBC=${PHP_ENABLE_PDO_ODBC:-"FALSE"}
PHP_ENABLE_PDO_SQLITE=${PHP_ENABLE_PDO_SQLITE:-"FALSE"}
PHP_ENABLE_PGSQL=${PHP_ENABLE_PGSQL:-"TRUE"}
PHP_ENABLE_PHAR=${PHP_ENABLE_PHAR:-"TRUE"}
PHP_ENABLE_POSIX=${PHP_ENABLE_POSIX:-"FALSE"}
PHP_ENABLE_PSPELL=${PHP_ENABLE_PSPELL:-"FALSE"}
PHP_ENABLE_RECODE=${PHP_ENABLE_RECODE:-"FALSE"}
PHP_ENABLE_REDIS=${PHP_ENABLE_REDIS:-"FALSE"}
PHP_ENABLE_SESSION=${PHP_ENABLE_SESSION:-"TRUE"}
PHP_ENABLE_SHMOP=${PHP_ENABLE_SHMOP:-"FALSE"}
PHP_ENABLE_SIMPLEXML=${PHP_ENABLE_SIMPLEXML:-"FALSE"}
PHP_ENABLE_SNMP=${PHP_ENABLE_SNMP:-"FALSE"}
PHP_ENABLE_SOAP=${PHP_ENABLE_SOAP:-"FALSE"}
PHP_ENABLE_SOCKETS=${PHP_ENABLE_SOCKETS:-"FALSE"}
PHP_ENABLE_SQLITE3=${PHP_ENABLE_SQLITE3:-"FALSE"}
PHP_ENABLE_TIDY=${PHP_ENABLE_TIDY:-"FALSE"}
PHP_ENABLE_TOKENIZER=${PHP_ENABLE_TOKENIZER:-"FALSE"}
PHP_ENABLE_WDDX=${PHP_ENABLE_WDDX:-"FALSE"}
PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG:-"FALSE"}
PHP_ENABLE_XML=${PHP_ENABLE_XML:-"TRUE"}
PHP_ENABLE_XMLREADER=${PHP_ENABLE_XMLREADER:-"TRUE"}
PHP_ENABLE_XMLRPC=${PHP_ENABLE_XMLRPC:-"FALSE"}
PHP_ENABLE_XMLWRITER=${PHP_ENABLE_XMLWRITER:-"FALSE"}
PHP_ENABLE_ZIP=${PHP_ENABLE_ZIP:-"FALSE"}
PHP_ENABLE_ZLIB=${PHP_ENABLE_ZLIB:-"TRUE"}
PHP_ENABLE_ZMQ=${PHP_ENABLE_ZMQ:-"FALSE"}
PHP_FPM_HOST=${PHP_FPM_HOST:-"localhost"}
PHP_FPM_LISTEN_PORT=${PHP_FPM_LISTEN_PORT:-9000}
PHP_FPM_MAX_CHILDREN=${PHP_FPM_MAX_CHILDREN:-75}
PHP_FPM_MAX_REQUESTS=${PHP_FPM_MAX_REQUESTS:-500}
PHP_FPM_MAX_SPARE_SERVERS=${PHP_FPM_MAX_SPARE_SERVERS:-3}
PHP_FPM_MIN_SPARE_SERVERS=${PHP_FPM_MIN_SPARE_SERVERS:-1}
PHP_FPM_PROCESS_MANAGER=${PHP_FPM_PROCESS_MANAGER:-"dynamic"}
PHP_FPM_START_SERVERS=${PHP_FPM_START_SERVERS:-2}
PHP_LOG_FILE=${PHP_LOG_FILE:-"php-fpm.log"}
PHP_LOG_LEVEL=${PHP_LOG_LEVEL:-"notice"}
PHP_LOG_LOCATION=${PHP_LOG_LOCATION:-"/www/logs/php-fpm"}
PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"128M"}
PHP_OPCACHE_MEM_SIZE=${PHP_OPCODE_MEM_SIZE:-"128"}
PHP_TIMEOUT=${PHP_TIMEOUT:-"180"}
PHP_UPLOAD_MAX_SIZE=${PHP_UPLOAD_MAX_SIZE:-"2G"}
PHP_VERSION=${PHP_VERSION:-`php-fpm7 -v | head -n 1 | awk '{print $2}'`}

### Adjust PHP Runtime Variables
sed -i -e "s#<PHP_LISTEN_PORT>#$PHP_FPM_LISTEN_PORT#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MAX_CHILDREN>#$PHP_FPM_MAX_CHILDREN#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MAX_EXECUTION_TIME>#$PHP_TIMEOUT#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MAX_REQUESTS>#$PHP_FPM_MAX_REQUESTS#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MAX_SPARE_SERVERS>#$PHP_FPM_MAX_SPARE_SERVERS#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MAX_START_SERVERS>#$PHP_FPM_START_SERVERS#g" /etc/php7/php-fpm.conf
sed -i -e "s#<MIN_SPARE_SERVERS>#$PHP_FPM_MIN_SPARE_SERVERS#g" /etc/php7/php-fpm.conf
sed -i -e "s#<PHP_HOST>#$PHP_FPM_HOST>#g" /etc/nginx/conf.d/default.conf
sed -i -e "s#<PHP_HOST>#${PHP_FPM_HOST}#g" /etc/nginx/nginx.conf.d/php-fpm.conf
sed -i -e "s#<PHP_LISTEN_PORT>#${PHP_FPM_LISTEN_PORT}#g" /etc/nginx/nginx.conf.d/php-fpm.conf
sed -i -e "s#<PHP_LOG_LOCATION>#$PHP_LOG_LOCATION#g" /etc/php7/php-fpm.conf
sed -i -e "s#<PHP_LOGFILE>#$PHP_LOG_FILE#g" /etc/php7/php-fpm.conf
sed -i -e "s#<PHP_MEMORY_LIMIT>#$PHP_MEMORY_LIMIT#g" /etc/php7/php-fpm.conf
sed -i -e "s#<PHP_TIMEOUT>#$PHP_TIMEOUT#g" /etc/nginx/nginx.conf.d/php-fpm.conf
sed -i -e "s#<PROCESS_MANAGER>#$PHP_FPM_PROCESS_MANAGER#g" /etc/php7/php-fpm.conf
sed -i -e "s#<UPLOAD_MAX_SIZE>#$UPLOAD_MAX_SIZE#g" /etc/php7/php-fpm.conf
sed -i -e "s#apc.shm_size.*#apc.shm_size=$PHP_APC_SHM_SIZE#g" /etc/php7/conf.d/apcu.ini
sed -i -e "s#opcache.memory_consumption.*#opcache.memory_consumption=$PHP_OPCACHE_MEM_SIZE#g" /etc/php7/conf.d/00_opcache.ini
sed -i -e "s#memory_limit = .*#memory_limit = $PHP_MEMORY_LIMIT#g" /etc/php7/php.ini
sed -i -e "s#max_input_time = .*#max_input_time = $PHP_TIMEOUT#g" /etc/php7/php.ini
sed -i -e "s#default_socket_timeout = .*#default_socket_timeout = $PHP_TIMEOUT#g" /etc/php7/php.ini
sed -i -e "s#post_max_size = .*#post_max_size = $PHP_UPLOAD_MAX_SIZE#g" /etc/php7/php.ini
sed -i -e "s#upload_max_filesize = .*#upload_max_filesize = $PHP_UPLOAD_MAX_SIZE#g" /etc/php7/php.ini
### Disable Opcache
if [ "$PHP_APC_SHM_SIZE" = "0" ]; then
  sed -i -e "s/apc.enabled=1/apc.enabled=0/g" /etc/php7/conf.d/acpu.ini
fi

if [ "$PHP_OPCACHE_MEM_SIZE" = "0" ]; then
  sed -i -e "s/opcache.enable=1/opcache.enable=0/g" /etc/php7/conf.d/00_opcache.ini
  sed -i -e "s/opcache.enable_cli=1/opcache.enable_cli=0/g" /etc/php7/conf.d/00_opcache.ini
fi

if [ "$PHP_ENABLE_ERRORS" != "TRUE" ]; then
  sed -i -e "\#php_flag[display_errors]#d" /etc/nginx/nginx.conf
fi

### Debug Mode
if [ "$PHP_ENABLE_XDEBUG" = "TRUE" ];  then
  PHP_XDEBUG_PROFILER_DIR=${PHP_XDEBUG_PROFILER_DIR:-"${PHP_LOG_DIR}/xdebug/"}
  PHP_XDEBUG_PROFILER_ENABLE=${PHP_XDEBUG_PROFILER_ENABLE:-"0"}
  PHP_XDEBUG_PROFILER_ENABLE_TRIGGER=${PHP_XDEBUG_PROFILER_ENABLE_TRIGGER:-"0"}
  PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-"1"}
  PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-"0"}  
  PHP_XDEBUG_REMOTE_ENABLE=${PHP_XDEBUG_REMOTE_ENABLE:-"1"}
  PHP_XDEBUG_REMOTE_HANDLER=${PHP_XDEBUG_REMOTE_HANDLER:-"dbgp"}
  PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-"127.0.0.1"}
  PHP_XDEBUG_REMOTE_PORT=${PHP_XDEBUG_REMOTE_PORT:-"9090"}

  sed -i -e "s/;zend_extension=xdebug.so/zend_extension=xdebug.so/g" /etc/php7/conf.d/xdebug.ini
  echo "xdebug.default_enable = 1" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.profiler_enable= ${PHP_XDEBUG_PROFILER_ENABLE}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.profiler_enable_trigger= ${PHP_XDEBUG_PROFILER_ENABLE_TRIGGER}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.profiler_output_dir='${PHP_XDEBUG_PROFILER_DIR}'" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_autostart = ${PHP_XDEBUG_REMOTE_AUTOSTART}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_connect_back = ${PHP_XDEBUG_REMOTE_CONNECT_BACK}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_enable = ${PHP_XDEBUG_REMOTE_ENABLE}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_handler = ${PHP_XDEBUG_REMOTE_HANDLER}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_host = ${PHP_XDEBUG_REMOTE_HOST}" >> /etc/php7/conf.d/xdebug.ini
  echo "xdebug.remote_port = ${PHP_XDEBUG_REMOTE_PORT}" >> /etc/php7/conf.d/xdebug.ini
  PHP_LOG_LEVEL=debug
  echo "** [php-fpm] DEBUGGING MODE ACTIVATED: Please use your IDE to connect to: {$PHP_XDEBUG_REMOTE_HOST}:{$PHP_XDEBUG_REMOTE_PORT}"
  if [ "$PHP_XDEBUG_PROFILER_ENABLE" = "1" ]; then
    echo "** [php-fpm] PROFILING MODE ACTIVATED: Please find the profiler logs at: $PHP_XDEBUG_PROFILER_DIR"
    mkdir -p $PHP_XDEBUG_PROFILER_DIR
    chown -R nginx $PHP_XDEBUG_PROFILER_DIR
  fi
fi



### SMTP Config
echo 'sendmail_path="/usr/bin/msmtp -C /etc/msmtp -t "' > /etc/php7/conf.d/smtp.ini

### Timezone Config
echo "date.timezone="`cat /etc/timezone` >> /etc/php7/conf.d/timezone.ini
sed -i -e "s#date.timezone = .*#date.timezone = `cat /etc/timezone`#g" /etc/php7/php.ini

### PHP Log Level
sed -i -e "s/<PHP_LOG_LEVEL>/$PHP_LOG_LEVEL/g" /etc/php7/php-fpm.conf
 
### Create Log Directories
mkdir -p ${PHP_LOG_LOCATION}
chown -R nginx ${PHP_LOG_LOCATION}

### Update Logrotate
sed -i -e "s#<PHP_LOG_LOCATION>#${PHP_LOG_LOCATION}#g" /etc/logrotate.d/php-fpm

#### Create Sample PHP File if doesn't exist
if [ "$PHP_ENABLE_CREATE_SAMPLE_PHP" = "TRUE" ]; then
  if [ ! -f "${NGINX_WEBROOT}/index.php" ] ; then
     echo "** [php-fpm] Creating sample index.php"
     mkdir -p ${NGINX_WEBROOT}
     cat <<EOF > ${NGINX_WEBROOT}/index.php
  <html>
  <title>Default Page</title>
  <h2>Container is working</h2>
  Congratulations! Your PHP-FPM image is working. You are seeing this because you don't have an index.php file in your ${NGINX_WEBROOT} directory.<br />
  <?php phpinfo();?>
  </html>
EOF
  fi
fi

#### Disable Extensions
if [ "$PHP_ENABLE_KITCHENSINK" = "FALSE" ] ; then
    unset PHP_ENABLE_CREATE_SAMPLE_PHP
    unset PHP_ENABLE_DISPLAY_ERRORS
    php_plugins_enabled=`set -o posix; set | sort | grep PHP_ENABLE_ | grep TRUE |sed -e 's/PHP_ENABLE_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
    echo "** [php-fpm] PHP-FPM Preparing to start with the following plugins enabled: ${php_plugins_enabled}"
    if [ "$PHP_ENABLE_SODIUM" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_sodium.ini; fi;
    if [ "$PHP_ENABLE_SOCKETS" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_sockets.ini; fi;
    if [ "$PHP_ENABLE_SQLITE3" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_sqlite3.ini; fi;
    if [ "$PHP_ENABLE_MONGODB" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/mongodb.ini; fi;
    if [ "$PHP_ENABLE_AMQP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/40_amqp.ini; fi;
    if [ "$PHP_ENABLE_APCU" != "TRUE" ]; then rm -rf /etc/php7/conf.d/apcu.ini ; fi;
    if [ "$PHP_ENABLE_BCMATH" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_bcmath.ini ; fi;
    if [ "$PHP_ENABLE_BZ2" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_bz2.ini; fi;
    if [ "$PHP_ENABLE_CALENDAR" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_calendar.ini; fi;
    if [ "$PHP_ENABLE_CTYPE" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_ctype.ini ; fi;
    if [ "$PHP_ENABLE_CURL" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_curl.ini ; fi;
    if [ "$PHP_ENABLE_DBA" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_dba.ini; fi;
    if [ "$PHP_ENABLE_DOM" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_dom.ini ; fi;
    if [ "$PHP_ENABLE_EMBED" != "TRUE" ]; then  : ; fi;
    if [ "$PHP_ENABLE_ENCHANT" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_enchant.ini ; fi;
    if [ "$PHP_ENABLE_EXIF" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/01_exif.ini; fi;
    if [ "$PHP_ENABLE_FILEINFO" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_fileinfo.ini; fi;
    if [ "$PHP_ENABLE_FTP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_ftp.ini; fi;
    if [ "$PHP_ENABLE_GD" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_gd.ini ; fi;
    if [ "$PHP_ENABLE_GETTEXT" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_gettext.ini; fi;
    if [ "$PHP_ENABLE_GMP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_gmp.ini; fi;
    if [ "$PHP_ENABLE_ICONV" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_iconv.ini ; fi;
    if [ "$PHP_ENABLE_IMAGICK" != "TRUE" ]; then rm -rf /etc/php7/conf.d/imagick.ini ; fi;
    if [ "$PHP_ENABLE_IGBINARY" != "TRUE" ]; then rm -rf /etc/php7/conf.d/10_igbinary.ini ; fi;      
    if [ "$PHP_ENABLE_IMAP" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_imap.ini ; fi;
    if [ "$PHP_ENABLE_INTL" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_intl.ini ; fi;
    if [ "$PHP_ENABLE_JSON" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_json.ini ; fi;
    if [ "$PHP_ENABLE_LDAP" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_ldap.ini ; fi;
    if [ "$PHP_ENABLE_MAILPARSE" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/60_mailparse.ini; fi;
    if [ "$PHP_ENABLE_MBSTRING" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_mbstring.ini ; fi;
    if [ "$PHP_ENABLE_MCRYPT" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_mcrypt.ini ; fi;
    if [ "$PHP_ENABLE_MEMCACHED" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/20_memcached.ini; fi;
    if [ "$PHP_ENABLE_MYSQLI" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/02_mysqli.ini; fi;
    if [ "$PHP_ENABLE_MYSQLND" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/01_mysqlnd.ini; fi;
    if [ "$PHP_ENABLE_ODBC" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_odbc.ini; fi;
    if [ "$PHP_ENABLE_OPCACHE" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_opcache.ini ; fi;
    if [ "$PHP_ENABLE_OPENSSL" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_openssl.ini ; fi;
    if [ "$PHP_ENABLE_PCNTL" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_pcntl.ini ; fi;
    if [ "$PHP_ENABLE_PDO" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_pdo.ini ; fi;
    if [ "$PHP_ENABLE_PDO_DBLIB" != "TRUE" ]; then rm -rf /etc/php7/conf.d/01_pdo_dblib.ini ; fi;      
    if [ "$PHP_ENABLE_PDO_MYSQL" != "TRUE" ]; then rm -rf /etc/php7/conf.d/02_pdo_mysql.ini ; fi;
    if [ "$PHP_ENABLE_PDO_PGSQL" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/01_pdo_pgsql.ini; fi;
    if [ "$PHP_ENABLE_PDO_ODBC" != "TRUE" ]; then rm -rf /etc/php7/conf.d/01_pdo_odbc.ini ; fi;
    if [ "$PHP_ENABLE_PDO_SQLITE" != "TRUE" ]; then rm -rf /etc/php7/conf.d/01_pdo_sqlite.ini ; fi;
    if [ "$PHP_ENABLE_PGSQL" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_pgsql.ini; fi;
    if [ "$PHP_ENABLE_PHAR" != "TRUE" ]; then rm -rf /etc/php7/conf.d/01_phar.ini ; fi;
    if [ "$PHP_ENABLE_POSIX" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_posix.ini; fi;
    if [ "$PHP_ENABLE_PSPELL" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_pspell.ini; fi;
    if [ "$PHP_ENABLE_RECODE" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_recode.ini; fi;
    if [ "$PHP_ENABLE_REDIS" != "TRUE" ]; then rm -rf /etc/php7/conf.d/20_redis.ini ; fi;
    if [ "$PHP_ENABLE_SESSION" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_session.ini ; fi;
    if [ "$PHP_ENABLE_SHMOP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_shmop.ini; fi;
    if [ "$PHP_ENABLE_SIMPLEXML" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_simplexml.ini; fi;
    if [ "$PHP_ENABLE_SNMP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_snmp.ini; fi;
    if [ "$PHP_ENABLE_SOAP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_soap.ini; fi;
    if [ "$PHP_ENABLE_TIDY" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_tidy.ini; fi;
    if [ "$PHP_ENABLE_TOKENIZER" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_tokenizer.ini; fi;
    if [ "$PHP_ENABLE_WDDX" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/01_wddx.ini; fi;
    if [ "$PHP_ENABLE_XDEBUG" != "TRUE" ]; then rm -rf /etc/php7/conf.d/xdebug.ini ; fi;
    if [ "$PHP_ENABLE_XML" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_xml.ini ; fi;
    if [ "$PHP_ENABLE_XMLREADER" != "TRUE" ]; then rm -rf /etc/php7/conf.d/01_xmlreader.ini ; fi;
    if [ "$PHP_ENABLE_XMLRPC" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/01_xmlrpc.ini; fi;
    if [ "$PHP_ENABLE_XMLWRITER" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_xmlwriter.ini; fi;
    if [ "$PHP_ENABLE_ZIP" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/00_zip.ini; fi;
    if [ "$PHP_ENABLE_ZLIB" != "TRUE" ]; then rm -rf /etc/php7/conf.d/00_zlib.ini ; fi;
    if [ "$PHP_ENABLE_ZMQ" != "TRUE" ]; then  rm -rf /etc/php7/conf.d/50_zmq.ini; fi;
else
  echo "** [php-fpm] Enabling Kitchen Sink mode and allowing all plugins to be active"
fi

if [ "$NGINX_AUTHENTICATION_TYPE" = "LLNG" ]; then
    sed -i '/ fastcgi_index/a\ \ \ \ \ \ \ \ include /etc/nginx/nginx.conf.d/authentication/llng_params;' /etc/nginx/conf.d/default.conf 
fi

chmod -R 0755 /etc/php7/
chown -R root:www-data /etc/php7/

touch /tmp/state/init-20-php-fpm