#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="php-fpm"
check_initialized

NGINX_WEBROOT=${NGINX_WEBROOT:-"/www/html"}
PHP_VERSION=${PHP_VERSION:-`php-fpm7 -v | head -n 1 | awk '{print $2}'`}
liftoff

print_info "Starting php-fpm ${PHP_VERSION}"
silent exec s6-setuidgid nginx php-fpm7 -F;
